
sudo: required

language: java

services:
  - docker

install:
  - cd Jabberpoint
  - ant

script:
  - ant test

after_script:
  - ant jar
  - cd ..
  - ./docker-latex.sh

deploy:
  local-dir: output
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
