
sudo: required

language: java

services:
  - docker

env:
  - LATEX_IMAGE="blang/latex:ubuntu"

before_script:
  - docker pull ${LATEX_IMAGE}

script:
  - ./build.sh

deploy:
  local-dir: output
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

