sudo: required

language: java

services:
  - docker

env:
  - IMAGE=blang/latex:ubuntu
  - TAG=${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}

before_script:
  - docker pull ${IMAGE}

script:
  - ./build.sh
