
sudo: required

language: java

services:
  - docker

install:
  - cd Jabberpoint
  - ant

script:
  - ant test
  - cd ..
  - ./docker-latex.sh

before_deploy:
  - cd Jabberpoint
  - ant jar

deploy:
  local-dir: output
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
