
sudo: required

language: java

services:
  - docker

addons:
  apt:
    packages:
      - junit

install:
  #- ./docker-latex.sh
  - cd Jabberpoint
  - ant

script:
  - ant test

deploy:
  local-dir: output
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

