sudo: required

language: java

services:
  - docker

env:
  - >
    LATEX_IMAGE="blang/latex:ubuntu"
    TAG=${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}

before_script:
  - docker pull ${LATEX_IMAGE}

script:
  - ./build.sh
