
sudo: required

language: java

services:
  - docker

env:
  global:
    - LATEX_IMAGE="blang/latex:ubuntu"
    - JAVA_IMAGE="openjdk:latest"

install:
  - docker pull ${LATEX_IMAGE}

script:
  - ./docker-latex.sh
  - ./build-java.sh

deploy:
  local-dir: output
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

