sudo: required

language: java

services:
  - docker

env:
  - IMAGE=blang/latex:ubuntu

before_script:
  - docker pull ${IMAGE}

script:
  - docker run --rm -it ${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER} --user="$(id -u):$(id -g)" --net=none --volume "${PWD}":/data "${IMAGE}" pdflatex Report/final-assignment-report.tex
